name: Test

on: [push]

jobs:
  build:
    runs-on: macos-latest

    env:
      MYSQL_HOST: "localhost"
      MYSQL_PORT: "9000"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "qwerty"
      API_URL: "https://localhost:9000/healthz" 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Install MySQL Server
        run: |
          sudo apt-get update -y
          sudo apt-get install -y mysql-server
        env:
          DEBIAN_FRONTEND: noninteractive
            
      - name: Create Database and User
        run: |
          sudo mysql -e "CREATE DATABASE csye6225;"
          sudo mysql -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'qwerty';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON mydatabase.* TO 'root'@'localhost';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Set up MySQL
        run: |
          sudo service mysql start
          mysql -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER -p $MYSQL_PASSWORD -e "CREATE DATABASE IF NOT EXISTS csye6225"

      - name: Start Node.js application
        run: npm start &

      - name: Wait for application to start
        run: sleep 10

      - name: Test API status
        run: |
          response_code=$(curl -sL -w "%{http_code}" $API_URL -o /dev/null)
          if [[ $response_code -eq 200 ]]; then
            echo "API is up and running with a 200 OK status code."
          else
            echo "API is not responding with a 200 OK status code. Status code: $response_code"
            exit 1
          fi
